#pragma once

enum ECombatZone
{
    COMBAT_ZONE_FRONT_FAR = 0x01,
    COMBAT_ZONE_FRONT_MIDDLE = 0x02,
    COMBAT_ZONE_FRONT_NEAR = 0x04,
    COMBAT_ZONE_LEFT = 0x08,
    COMBAT_ZONE_RIGHT = 0x10,
    COMBAT_ZONE_REAR = 0x20,
    COMBAT_ZONE_NO_ZONE = 0x40,
    COMBAT_ZONE_OUTER_RING = 0x80,
    COMBAT_ZONE_ALL_ZONES = 0xFF
};
