#pragma once

enum ECreatureAbility
{
    CREATURE_ABILITY_TYPE_ATTACK,
    CREATURE_ABILITY_TYPE_FLOURISH,
    CREATURE_ABILITY_TYPE_FLOURISH_360_CW,
    CREATURE_ABILITY_TYPE_FLOURISH_360_ACW,
    CREATURE_ABILITY_TYPE_FLOURISH_UPTHRUST_LEFT,
    CREATURE_ABILITY_TYPE_FLOURISH_UPTHRUST_RIGHT,
    CREATURE_ABILITY_TYPE_FLOURISH_MAXIMUM_DAMAGE,
    CREATURE_ABILITY_TYPE_BREAK_BLOCK,
    MAX_NUMBER_OF_CREATURE_ABILITIES
};
